annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 3489 bytes
          !
          ! Last configuration change at 19:35:00 UTC Fri Nov 1 2024
          !
          version 15.2
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          service compress-config
          !
          hostname source-switch
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          username cisco privilege 15 secret 5 $1$A5br$xhQ/2h/0iji2PfveTY1na0
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          ip domain-name guido.com
          ip cef
          no ipv6 cef
          !
          !
          !
          spanning-tree mode pvst
          spanning-tree extend system-id
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           no switchport
           ip address 192.168.201.20 255.255.255.0
           negotiation auto
          !
          interface GigabitEthernet0/1
           negotiation auto
          !
          interface GigabitEthernet0/2
           negotiation auto
          !
          interface GigabitEthernet0/3
           negotiation auto
          !
          interface GigabitEthernet1/0
           negotiation auto
          !
          interface GigabitEthernet1/1
           negotiation auto
          !
          interface GigabitEthernet1/2
           negotiation auto
          !
          interface GigabitEthernet1/3
           negotiation auto
          !
          interface GigabitEthernet2/0
           negotiation auto
          !
          interface GigabitEthernet2/1
           negotiation auto
          !
          interface GigabitEthernet2/2
           negotiation auto
          !
          interface GigabitEthernet2/3
           negotiation auto
          !
          interface GigabitEthernet3/0
           negotiation auto
          !
          interface GigabitEthernet3/1
           negotiation auto
          !
          interface GigabitEthernet3/2
           negotiation auto
          !
          interface GigabitEthernet3/3
           negotiation auto
          !
          ip forward-protocol nd
          !
          ip http server
          ip http secure-server
          !
          ip route 0.0.0.0 0.0.0.0 192.168.201.1
          ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          !
          !
          !
          !
          !
          !
          control-plane
          !
          banner exec ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner incoming ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner login ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login local
           transport input ssh
          !
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: source-switch
    node_definition: iosvl2
    parameters: {}
    ram: null
    tags: []
    x: -280
    y: 80
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet1/0
        slot: 4
        type: physical
      - id: i6
        label: GigabitEthernet1/1
        slot: 5
        type: physical
      - id: i7
        label: GigabitEthernet1/2
        slot: 6
        type: physical
      - id: i8
        label: GigabitEthernet1/3
        slot: 7
        type: physical
      - id: i9
        label: GigabitEthernet2/0
        slot: 8
        type: physical
      - id: i10
        label: GigabitEthernet2/1
        slot: 9
        type: physical
      - id: i11
        label: GigabitEthernet2/2
        slot: 10
        type: physical
      - id: i12
        label: GigabitEthernet2/3
        slot: 11
        type: physical
      - id: i13
        label: GigabitEthernet3/0
        slot: 12
        type: physical
      - id: i14
        label: GigabitEthernet3/1
        slot: 13
        type: physical
      - id: i15
        label: GigabitEthernet3/2
        slot: 14
        type: physical
      - id: i16
        label: GigabitEthernet3/3
        slot: 15
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: unmanaged-switch-0
    node_definition: unmanaged_switch
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: 80
    interfaces:
      - id: i0
        label: port0
        slot: 0
        type: physical
      - id: i1
        label: port1
        slot: 1
        type: physical
      - id: i2
        label: port2
        slot: 2
        type: physical
      - id: i3
        label: port3
        slot: 3
        type: physical
      - id: i4
        label: port4
        slot: 4
        type: physical
      - id: i5
        label: port5
        slot: 5
        type: physical
      - id: i6
        label: port6
        slot: 6
        type: physical
      - id: i7
        label: port7
        slot: 7
        type: physical
  - boot_disk_size: null
    configuration:
      - name: default
        content: System Bridge
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: ext-conn-0
    node_definition: external_connector
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: -80
    interfaces:
      - id: i0
        label: port
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 3494 bytes
          !
          ! Last configuration change at 19:35:16 UTC Fri Nov 1 2024
          !
          version 15.2
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          service compress-config
          !
          hostname destination-switch
          !
          boot-start-marker
          boot-end-marker
          !
          !
          no logging console
          !
          username cisco privilege 15 secret 5 $1$79kf$h5Kqb5a3YJS.MPKDBQoMl1
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          ip domain-name guido.com
          ip cef
          no ipv6 cef
          !
          !
          !
          spanning-tree mode pvst
          spanning-tree extend system-id
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           no switchport
           ip address 192.168.201.21 255.255.255.0
           negotiation auto
          !
          interface GigabitEthernet0/1
           negotiation auto
          !
          interface GigabitEthernet0/2
           negotiation auto
          !
          interface GigabitEthernet0/3
           negotiation auto
          !
          interface GigabitEthernet1/0
           negotiation auto
          !
          interface GigabitEthernet1/1
           negotiation auto
          !
          interface GigabitEthernet1/2
           negotiation auto
          !
          interface GigabitEthernet1/3
           negotiation auto
          !
          interface GigabitEthernet2/0
           negotiation auto
          !
          interface GigabitEthernet2/1
           negotiation auto
          !
          interface GigabitEthernet2/2
           negotiation auto
          !
          interface GigabitEthernet2/3
           negotiation auto
          !
          interface GigabitEthernet3/0
           negotiation auto
          !
          interface GigabitEthernet3/1
           negotiation auto
          !
          interface GigabitEthernet3/2
           negotiation auto
          !
          interface GigabitEthernet3/3
           negotiation auto
          !
          ip forward-protocol nd
          !
          ip http server
          ip http secure-server
          !
          ip route 0.0.0.0 0.0.0.0 192.168.201.1
          ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          !
          !
          !
          !
          !
          !
          control-plane
          !
          banner exec ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner incoming ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner login ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
           exec-timeout 0 0
           login local
           transport input ssh
          !
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: destination-switch
    node_definition: iosvl2
    parameters: {}
    ram: null
    tags: []
    x: 200
    y: 80
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet1/0
        slot: 4
        type: physical
      - id: i6
        label: GigabitEthernet1/1
        slot: 5
        type: physical
      - id: i7
        label: GigabitEthernet1/2
        slot: 6
        type: physical
      - id: i8
        label: GigabitEthernet1/3
        slot: 7
        type: physical
      - id: i9
        label: GigabitEthernet2/0
        slot: 8
        type: physical
      - id: i10
        label: GigabitEthernet2/1
        slot: 9
        type: physical
      - id: i11
        label: GigabitEthernet2/2
        slot: 10
        type: physical
      - id: i12
        label: GigabitEthernet2/3
        slot: 11
        type: physical
      - id: i13
        label: GigabitEthernet3/0
        slot: 12
        type: physical
      - id: i14
        label: GigabitEthernet3/1
        slot: 13
        type: physical
      - id: i15
        label: GigabitEthernet3/2
        slot: 14
        type: physical
      - id: i16
        label: GigabitEthernet3/3
        slot: 15
        type: physical
links:
  - id: l0
    n1: n0
    n2: n1
    i1: i1
    i2: i0
    conditioning: {}
    label: source-switch-GigabitEthernet0/0<->unmanaged-switch-0-port0
  - id: l1
    n1: n1
    n2: n2
    i1: i1
    i2: i0
    conditioning: {}
    label: unmanaged-switch-0-port1<->ext-conn-0-port
  - id: l2
    n1: n3
    n2: n1
    i1: i1
    i2: i2
    conditioning: {}
    label: iosvl2-0-GigabitEthernet0/0<->unmanaged-switch-0-port2
lab:
  description: ''
  notes: ''
  title: Switch config copy
  version: 0.2.2
